""" Project column names. """


medallion = 'medallion'
hack_license = 'hack_license'
vendor_id = 'vendor_id'
pickup_datetime = 'pickup_datetime'
payment_type = 'payment_type'
fare_amount = 'fare_amount'
surcharge = 'surcharge'
mta_tax = 'mta_tax'
tip_amount = 'tip_amount'
tolls_amount = 'tolls_amount'
total_amount = 'total_amount'
rate_code = 'rate_code'
store_and_fwd_flag = 'store_and_fwd_flag'
dropoff_datetime = 'dropoff_datetime'
passenger_count = 'passenger_count'
trip_time_in_secs = 'trip_time_in_secs'
trip_distance = 'trip_distance'
pickup_longitude = 'pickup_longitude'
pickup_latitude = 'pickup_latitude'
dropoff_longitude = 'dropoff_longitude'
dropoff_latitude = 'dropoff_latitude'
